//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypiconOnline.Domain.Calendar
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IValidatable 
	{
		bool IsValid { get;set; }

		void Validate();

	}
}

