//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypiconOnline.Domain.Calendar
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OktoikhDay : Day
	{
		public virtual byte Glas
		{
			get;
			set;
		}

		public virtual DateTime.DayOfWeek DayOfWeek
		{
			get;
			set;
		}

	}
}

