//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypiconOnline.Domain.Calendar
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Sign : IServiced, IBookElement
	{
		public virtual byte SignNumber
		{
			get;
			set;
		}

		public virtual bool IsTemplate
		{
			get;
			set;
		}

		public virtual Sign Template
		{
			get;
			set;
		}

	}
}

