//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Core.Days
{
    public class MenologyDayBusinessConstraint
    {
        public static readonly BusinessConstraint MenologyDayNameRequired = new BusinessConstraint("Должно быть определено имя.");
    }
}
