//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace TypiconOnline.Domain.Core.Days
{
    public class TriodionDay : Day
    {
        public virtual int DaysFromEaster
        {
            get;
            set;
        }

        //public virtual int HasMinea
        //{
        //    get;
        //    set;
        //}

        protected override void Validate()
        {
            base.Validate();
        }
    }
}

