//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Typicon.Modifications
{
    public abstract class ModifiedRule : EntityBase<int>, IAggregateRoot, IComparable<ModifiedRule>
    {
        public DateTime Date { get; set; }
        //public DayType Day { get; set; }

        public int Priority { get; set; }

        public bool IsLastName { get; set; }

        public string ShortName { get; set; }

        public bool AsAddition { get; set; }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Сравнение идет по свойству Priority, чем меньше целочисленное значение, тем выше приоритет
        /// </summary>
        /// <param name="other"></param>
        /// <returns></returns>
        public int CompareTo(ModifiedRule other)
        {
            if (Priority < other.Priority)
                return -1;
            else if (other.Priority == Priority)
                return 0;
            else return 1;
        }
    }
}

