//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TypiconOnline.Domain.Days;

namespace TypiconOnline.Domain.Typicon.Modifications
{
    public class ModifiedMenologyRule : ModifiedRule
    {
        public MenologyRule RuleEntity { get; set; }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}

