//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Typicon.Modifications
{
    public abstract class ModifiedRule : EntityBase<int>, IAggregateRoot
    {
        public DateTime Date { get; set; }
        //public DayType Day { get; set; }

        public int Priority { get; set; }

        public bool IsLastName { get; set; }

        public string ShortName { get; set; }

        public bool AsAddition { get; set; }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}

