//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class IsExistsBusinessConstraint
    {
        public static readonly BusinessConstraint YmnosRuleReqiured 
            = new BusinessConstraint(string.Format("Отсутствуют дочерний элемент {0}.", RuleConstants.YmnosRuleNode));
    }
}
