//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class KKatavasiaRuleBusinessConstraint
    {
        
        public static readonly BusinessConstraint InvalidName = new BusinessConstraint("Определение катавасии отсутствует в хранилище.");
        public static readonly BusinessConstraint DoubleDefinition = new BusinessConstraint("Необходимо одно определение: либо ссылка на источник и канон службы, либо катавасию из хранилища.");
    }
}
