//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class KKontakionRuleBusinessConstraint
    {
        
        public static readonly BusinessConstraint SourceRequired = new BusinessConstraint("Отсутствует или не верно определен источник песнопения (книги).");
        public static readonly BusinessConstraint KanonasRequired = new BusinessConstraint("Отсутствует или не верно определен канон в источнике песнопения (книги).");
    }
}
