//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class TheotokionRuleBusinessConstraint
    {
        public static readonly BusinessConstraint ChildRequired = new BusinessConstraint("Отсутствуют определение дочернего элемента.");
    }
}
