//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Days
{
    public class IrmologionTheotokionBusinessConstraint
    {
        public static readonly BusinessConstraint InvalidIhos = new BusinessConstraint("Неверно определен глас песнопения.");
    }
}
