//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules
{
    public class RuleContainerBusinessConstraint
    {
        public static readonly BusinessConstraint DefinitionContainerChildrenRequired = new BusinessConstraint("Правило не содержит элементов.");
    }
}
