//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class DaysFromEasterBusinessConstraint
    {
        public static readonly BusinessConstraint DateAbsense = new BusinessConstraint("Отсутствует определение даты.");
    }
}
