//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class GetClosestDayBusinessConstraint
    {
        public static readonly BusinessConstraint AttributesRequired = new BusinessConstraint("Отсутствуют определения дня недели и количества недель.");
        public static readonly BusinessConstraint DayOfWeekRequired = new BusinessConstraint("Отсутствуют определение дня недели.");
        public static readonly BusinessConstraint DayOfWeekWrongDefinition = new BusinessConstraint("Неверное определение дня недели.");
        public static readonly BusinessConstraint WeekCountRequired = new BusinessConstraint("Отсутствуют определение количества недель.");
        public static readonly BusinessConstraint WeekCountWrongDefinition = new BusinessConstraint("Неверное определение количества недель.");
        public static readonly BusinessConstraint DateRequired = new BusinessConstraint("Отсутствуют определение даты.");
        public static readonly BusinessConstraint DatesTooMuch = new BusinessConstraint("Более одного определения даты.");
    }
}
