//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class GetDayOfWeekBusinessConstraint
    {
        public static readonly BusinessConstraint TermsTooMuch = new BusinessConstraint("Более одного определения параметра.");
        public static readonly BusinessConstraint TermsRequired = new BusinessConstraint("Отсутствуют определения дня недели.");
        public static readonly BusinessConstraint DayOfWeekWrongDefinition = new BusinessConstraint("Неверное определение дня недели.");
    }
}
