//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using TypiconOnline.Domain.Interfaces;
using TypiconOnline.Domain.ItemTypes;
using TypiconOnline.Domain.Rules.Handlers;
using TypiconOnline.Domain.Rules.Interfaces;
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class Int : IntExpression
    {
        public Int(string name) : base(name) { }

        private int _valueExpression;

        public virtual int ValueExpression
        {
            get
            {
                return ValueCalculated;
            }
            set
            {
                ValueCalculated = value;
            }
        }

        protected override void InnerInterpret(IRuleHandler handler)
        {
            //ничего
        }

        protected override void Validate() { }
    }
}

