//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class LogicalExpressionBusinessConstraint
    {
        public static readonly BusinessConstraint ChildrenRequired = new BusinessConstraint("Отсутствуют или неверно определны дочерние элементы.");
        public static readonly BusinessConstraint NotEnoughChildren = new BusinessConstraint("Дочерних элементов должно быть хотя бы два.");
        public static readonly BusinessConstraint InvalidChild = new BusinessConstraint("Дочерний элемент неверно определен.");
        public static readonly BusinessConstraint TypeBooleanMismatch = new BusinessConstraint("Дочерний элемент должен быть булевского типа.");
        public static readonly BusinessConstraint TypeMismatch = new BusinessConstraint("Дочерние элементы должны быть одного типа.");
    }
}
