//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TypiconOnline.Domain.Rules.Expressions
{ 
    /*public interface IRuleOutputElement  : RuleElement
    {
	    object OutputValue { get; }

	    IRuleOutputElement InputValue { get;set; }

	    Type OutputType { get; }

	    bool Equals(IRuleOutputElement obj);

    }*/

    public abstract class RuleExpression<TExpr, TOutput> : RuleElementBase
    {
        protected TExpr _valueExpression;

        protected TOutput _valueCalculated;

        public virtual TExpr ValueExpression {
            get
            {
                return _valueExpression;
            }
        }

        public virtual TOutput ValueCalculated
        {
            get
            {
                return _valueCalculated;
            }
        }
        public virtual TExpr ExpressionType { get; }

        public override bool Equals(object entity)
        {
            return entity != null
               && entity is RuleExpression<TExpr, TOutput>
               && this.ValueCalculated.Equals(((RuleExpression<TExpr, TOutput>)entity).ValueCalculated);
               //&& this == (RuleExpression<ExpType>)entity;
        }

        public override int GetHashCode()
        {
            return this.ExpressionType.GetHashCode();
        }

        //public bool OutputTypeEquals(RuleExpression obj)
        //{
        //    if (obj == null)
        //        return false;

        //    return OutputType.Equals(obj.OutputType);
        //}

        //public bool OutputValueEquals(RuleExpression obj)
        //{
        //    if (obj == null)
        //        return false;

        //    if (OutputType.Equals(obj.OutputType))
        //    {
        //        return OutputValue.Equals(obj.OutputValue);
        //    }

        //    return false;
        //}
    }
}

