//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TypiconOnline.Domain.Days;

namespace TypiconOnline.Domain.Books.Oktoikh
{
    public class OktoikhDay : DayService
    {
    }
}

