//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Days
{
    public class KontakionBusinessConstraint
    {
        public static readonly BusinessConstraint YmnosRequired = new BusinessConstraint("Текст конадака обязателен для заполнения.");
    }
}
