//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using TypiconOnline.Domain.ItemTypes;
using TypiconOnline.Domain.Rules.Handlers;
using TypiconOnline.Infrastructure.Common.Domain;
using TypiconOnline.Domain.Interfaces;
using TypiconOnline.Domain.Books;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class DaysFromEaster : Int
    {
        private DateExpression _childDateExp;

        public DaysFromEaster(XmlNode node) : base(node)
        {
            if (node.HasChildNodes)
            {
                _childDateExp = Factories.RuleFactory.CreateDateExpression(node.FirstChild);
            }
        }

        protected override void InnerInterpret(DateTime date, IRuleHandler handler)
        {
            DateTime easterDate = BookStorage.Instance.Easters.GetCurrentEaster(date.Year);

            _childDateExp.Interpret(date, handler);

            //DateTime easterDate = handler.GetCurrentEaster(date.Year);

            _valueCalculated = ((DateTime)_childDateExp.ValueCalculated).Subtract(easterDate).Days;
            _valueExpression = new ItemInt((int)_valueCalculated);
        }

        protected override void Validate()
        {
            if (_childDateExp == null)
            {
                AddBrokenConstraint(DaysFromEasterBusinessConstraint.DateAbsense, ElementName);
            }
            else
            {
                if (_childDateExp.IsValid)
                {
                    foreach (BusinessConstraint brokenRule in _childDateExp.GetBrokenConstraints())
                    {
                        AddBrokenConstraint(brokenRule, ElementName + "." + RuleConstants.DateNodeName + "." + brokenRule.ConstraintPath);
                    }
                }
            }
        }
    }
}

