//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Expressions
{
    public class IntBusinessConstraint
    {
        public static readonly BusinessConstraint IntTypeMismatch = new BusinessConstraint("Неверный формат целого числа.");
    }
}
