//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TypiconOnline.Domain.Rules;

namespace TypiconOnline.Domain.Typicon
{
    public class CommonRule : RuleEntity
    {
        public virtual Sign Template { get; set; }

        public virtual TypiconEntity Owner { get; set; }
        /// <summary>
        /// Возвращает Правило: либо свое, либо шаблонное
        /// </summary>
        public override RuleContainer Rule
        {
            get
            {
                if ((base.Rule == null) && string.IsNullOrEmpty(RuleDefinition))
                {
                    return Template.Rule;
                }

                return base.Rule;//(string.IsNullOrEmpty(RuleDefinition)) ? Template.Rule : null;
            }
        }
        
    }
}

