//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Books.Elements
{
    public class DayContainerBusinessConstraint
    {
        public static readonly BusinessConstraint NameRequired = new BusinessConstraint("Имя обязательно для заполнения.");
        public static readonly BusinessConstraint TroparionRequired = new BusinessConstraint("Тропарь должен быть определен либо в чине Малой вечерни, либо Вечерни.");
    }
}
