//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Books.Elements
{
    public class EvangelionPartBusinessConstraint
    {
        public static readonly BusinessConstraint InvalidNumber = new BusinessConstraint("Номер зачала должен иметь положительное значение.");
    }
}
