//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Books.Elements
{
    public class SixHourBusinessConstraint
    {
        public static readonly BusinessConstraint TroparionRequired = new BusinessConstraint("Наличие тропаря пророчества обязательно.");
        public static readonly BusinessConstraint ProkeimenRequired = new BusinessConstraint("Наличие прокимна обязательно.");
        public static readonly BusinessConstraint ParoimiaRequired = new BusinessConstraint("Наличие паремии обязательно.");
    }
}
