//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Books.Elements
{
    public class YmnosBusinessConstraint
    {
        public static readonly BusinessConstraint TextRequired = new BusinessConstraint("Текст песнопения обязателен для заполнения.");
    }
}
