//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;

namespace TypiconOnline.Domain.Rules.Executables
{
    /// <summary>
    /// Абстрактный класс для "исполняемых" элементов, 
    /// т.е. которым преполагается назначение какого-либо функционала.
    /// </summary>
    public abstract class RuleExecutable : RuleElement
    {
        public RuleExecutable() { }
        public RuleExecutable(string name) : base(name) { }
        public RuleExecutable(XmlNode node) : base(node)
        {
        }
    }
}

