//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Books.TheotokionApp
{
    public class TheotokionAppBusinessConstraint
    {
        public static readonly BusinessConstraint InvalidIhos = new BusinessConstraint("Неверно определен глас песнопения.");
        public static readonly BusinessConstraint EmptyStringDefinition = new BusinessConstraint("Отсутствует определение песнопения.");
    }
}
