//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain
{
    public class RuleEntityBusinessConstraint
    {
        public static readonly BusinessConstraint RuleRequired = new BusinessConstraint("Правило должно быть определено.");
    }
}
