//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class EktenisBusinessConstraint
    {
        public static readonly BusinessConstraint NameReqiured = new BusinessConstraint("Отсутствуют определение имени.");
    }
}
