//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class KSedalenRuleBusinessConstraint
    {
        
        public static readonly BusinessConstraint PlaceRequired = new BusinessConstraint("Отсутствуют определение места в каноне.");
    }
}
