//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Schedule
{
    public class TextHolderBusinessConstraint
    {
        public static readonly BusinessConstraint ParagraphRequired = new BusinessConstraint("Отсутствуют определение параграфа с текстом.");
        public static readonly BusinessConstraint ParagraphEmpty = new BusinessConstraint("Параграф не содержит определений текста.");

        public static readonly BusinessConstraint KindMismatch = new BusinessConstraint("Отсутствуют определение типа песнопения (обычный, славник, богородичен...).");
        public static readonly BusinessConstraint SourceRequired = new BusinessConstraint("Отсутствуют определение источника песнопения (книги).");
        public static readonly BusinessConstraint SourceInvalid = new BusinessConstraint("Неверный источник песнопения (книги).");
        
        public static readonly BusinessConstraint PlaceInvalid = new BusinessConstraint("Неверно определено место в источнике песнопения (книги).");
    }
}
