//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Executables
{
    public class ModifyReplacedDayBusinessConstraint
    {
        public static readonly BusinessConstraint KindUndefined = new BusinessConstraint("Тип изменяемого правила не определен.");
    }
}
