//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Executables
{
    public class SwitchBusinessConstraint
    {
        public static readonly BusinessConstraint ConditionRequired = new BusinessConstraint("Должно быть определено условие.");
        public static readonly BusinessConstraint CaseRequired = new BusinessConstraint("Должно быть определено хотя бы одно значение выбора.");
        public static readonly BusinessConstraint ConditionsTypeMismatch = new BusinessConstraint("Условие и значения должны быть одного типа.");
    }
}
