//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Days
{
    public class DayContainerBusinessConstraint
    {
        public static readonly BusinessConstraint NameRequired = new BusinessConstraint("Имя обязательно для заполнения.");
    }
}
