//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Days
{
    public class DayElementsContainerBusinessConstraint
    {
        public static readonly BusinessConstraint OnlyDayElementsAlowed = new BusinessConstraint("Дочерними элементами могут быть только определения богослужебных текстов дня.");
    }
}
