//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules.Days
{
    public class OdiBusinessConstraint
    {
        public static readonly BusinessConstraint InvalidNumber = new BusinessConstraint("Нверный номер песни (допустимые значения с 1 до 9).");
        public static readonly BusinessConstraint IrmosRequired = new BusinessConstraint("ирмос канона обязателен для заполнения.");
    }
}
