//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Day
{
	public virtual object ID
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual Sign Sign
	{
		get;
		set;
	}

	public virtual bool HasRule
	{
		get;
		set;
	}

	public virtual object RuleDefinition
	{
		get;
		set;
	}

	public virtual Rule Rule
	{
		get;
		set;
	}

	public virtual Sign ServiceSign
	{
		get;
		set;
	}

	public virtual void Validate()
	{
		throw new System.NotImplementedException();
	}

}

