//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Service
{
	public virtual object ID
	{
		get;
		set;
	}

	public virtual object Owner
	{
		get;
		set;
	}

	public virtual object Time
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual bool IsDayBefore
	{
		get;
		set;
	}

	public virtual object AdditionalName
	{
		get;
		set;
	}

	public virtual string TimeStyle
	{
		get;
		set;
	}

	public virtual string NameStyle
	{
		get;
		set;
	}

}

