//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TypiconFolder : BaseFolder<CommonRule>
{
    public virtual TypiconFolder Parent { get; set; }
	public virtual TypiconEntity Owner { get; set; }
}

