//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using TypiconOnline.Domain.Rules.Handlers;
using TypiconOnline.Domain.Typicon;
using TypiconOnline.Infrastructure.Common.Domain;

namespace TypiconOnline.Domain.Rules
{
    public abstract class RuleElement : ValueObjectBase
    {
        //RuleElement ParentElement { get;set; }

        protected string ElementName { get; set; }

        public RuleElement() { }

        public RuleElement(XmlNode node)
        {
            if (node != null)
            {
                ElementName = node.Name;
            }
        }

        protected bool _isInterpreted = false;

        public virtual void Interpret(DateTime date, IRuleHandler handler)
        {
            _isInterpreted = true;
        }


        public bool IsInterpreted
        {
            get
            {
                return _isInterpreted;
            }
        }

    }
}

